<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>71f3e645-1f5d-4d82-b062-6ab82d585793</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.30" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.80.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Google" Version="1.80.0-alpha" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
